version: "3"

services:
  mysql_serve:
    image: mysql:5.6.42
    container_name: micro_db_api_gateway
    ports:
      - 34660:3306
    environment:
      MYSQL_USER: desarrollo
      MYSQL_PASSWORD: kevin123
      MYSQL_DATABASE: micro_api_gateway
      MYSQL_ROOT_PASSWORD: kevin123
  web:
    build: .
    container_name: micro_api_gateway
    ports:
      - 8003:80
    volumes:
      - .:/opt/data
    links:
      - mysql_serve
